use correct version of jsr module
because there is no stable release yet, importing from "@extism/extism" without the version will error

```
error: Could not find constraint in the list of versions: @extism/extism
  Specifier: jsr:@extism/extism
```